"""
Django settings for gespro project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path
from dotenv import load_dotenv
import os

# Cargar variables desde .env lo antes posible para que estén disponibles
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(BASE_DIR / "frontend"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1+3@n368!w5*v_p4hm8#)qv(u18l!gjk0&5b4pa(khn)g9u+t('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '146.83.216.166', 'gespro.inf.uach.cl','testserver']

CSRF_TRUSTED_ORIGINS = ['https://gespro.inf.uach.cl']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'tailwind',
    'widget_tweaks',
    'theme',
    'proyectos',
    'alertas.apps.AlertasConfig',
    'vistas',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'django.contrib.sites',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

ROOT_URLCONF = 'gespro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'gespro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('POSTGRES_DB', 'gespro'),
#         'USER': os.getenv('POSTGRES_USER', 'albaca'),
#         'PASSWORD': os.getenv('POSTGRES_PASSWORD', '9E5Og5yodW6u0S'),
#         'HOST': os.getenv('DB_HOST', 'gespro-db'),
#         'PORT': os.getenv('POSTGRES_PORT', '5003'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR /'databases'/ 'db.sqlite3',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'
if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]


Q_CLUSTER = {
    "name": "DjangoQ",
    "workers": 4,        
    "recycle": 500,
    "timeout": 60,
    "retry": 120,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}

# EMAIL_MODE = os.getenv("EMAIL_MODE", "dummy")

# if EMAIL_MODE == "dummy":
#     EMAIL_BACKEND = "django.core.mail.backends.dummy.EmailBackend"
# elif EMAIL_MODE == "console":
#     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# elif EMAIL_MODE == "smtp": # Especificamos smtp claramente
#     EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#     EMAIL_HOST = os.getenv("SMTP_SERVER")
#     EMAIL_PORT = 587
#     EMAIL_USE_TLS = True
#     EMAIL_HOST_USER = os.getenv("EMAIL")
#     # Limpiamos la contraseña por si acaso tiene espacios del .env
#     EMAIL_HOST_PASSWORD = os.getenv("PASSWORD_APP").replace(" ", "") 
#     DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# #allauth settings
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False

# # Usar email como identificador
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = "email"

# # Crear cuenta automáticamente sin pantalla intermedia
# SOCIALACCOUNT_AUTO_SIGNUP = True

# # Tomar nombre y email desde Google
# SOCIALACCOUNT_QUERY_EMAIL = True
# LOGIN_REDIRECT_URL = '/proyectos'

# MIDDLEWARE.insert(
#     MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
#     'gespro.middleware.LoginRequiredMiddleware'
# )

# # Lista blanca de correos permitidos
# ALLOWED_GOOGLE_EMAILS = [
#     "isaiasgoku15@gmail.com",
#     "otrocorreo@empresa.com",
# ]
# ACCOUNT_ADAPTER = "proyectos.verificadorUsuarios.MyAccountAdapter"

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
